//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra
    {
        public int id_compras { get; set; }
        public string nm_produto { get; set; }
        public int qts_produtos { get; set; }
        public decimal vl_total { get; set; }
        public decimal ds_frete { get; set; }
        public System.DateTime dt_compra { get; set; }
    }
}
