//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_controle_ponto
    {
        public int id_controle_ponto { get; set; }
        public int id_funcionario { get; set; }
        public System.DateTime hr_entrada { get; set; }
        public System.DateTime hr_intervalo { get; set; }
        public System.DateTime hr_retorno { get; set; }
        public System.DateTime hr_saida { get; set; }
        public System.DateTime dt_dia { get; set; }
    
        public virtual tb_funcionario tb_funcionario { get; set; }
    }
}
