//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_despesa
    {
        public int id_despesa { get; set; }
        public decimal vl_valor { get; set; }
        public string ds_descricao { get; set; }
        public System.DateTime dt_vencimento { get; set; }
    }
}
