//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        public int id_fornecedor { get; set; }
        public string nm_fornecedor { get; set; }
        public decimal nm_CNPJ_CPF { get; set; }
        public string ds_endereço { get; set; }
        public decimal ds_telefone { get; set; }
        public string ds_email { get; set; }
        public string nm_produto { get; set; }
    }
}
