//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido
    {
        public int id_pedido { get; set; }
        public string nm_pedido { get; set; }
        public string nm_pedinte { get; set; }
        public System.DateTime dt_pedido { get; set; }
    }
}
