//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public int id_usuario { get; set; }
        public string nm_usuario { get; set; }
        public string nm_senha { get; set; }
        public string ds_email { get; set; }
        public string ds_cargo { get; set; }
        public string ds_recuperacao { get; set; }
    }
}
