//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda_item
    {
        public int id_venda { get; set; }
        public int id_produto_v { get; set; }
        public int id_venda_d { get; set; }
    
        public virtual tb_produto_venda tb_produto_venda { get; set; }
        public virtual tb_venda tb_venda { get; set; }
    }
}
