//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicJoy.Entityes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venda_item1
    {
        public int id_venda { get; set; }
        public int tb_produto_venda_id_produto { get; set; }
        public int tb_venda_id_venda { get; set; }
    
        public virtual tb_produto_venda1 tb_produto_venda { get; set; }
        public virtual tb_venda1 tb_venda { get; set; }
    }
}
